// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaAdministracao.Data;

#nullable disable

namespace SistemaAdministracao.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116190831_AddSistemaRelacionamento")]
    partial class AddSistemaRelacionamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaAdministracao.Models.Papel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("IdSistema")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdSistema");

                    b.ToTable("Papeis");
                });

            modelBuilder.Entity("SistemaAdministracao.Models.PapelPermissao", b =>
                {
                    b.Property<int>("IdPapel")
                        .HasColumnType("integer");

                    b.Property<int>("IdPermissao")
                        .HasColumnType("integer");

                    b.HasKey("IdPapel", "IdPermissao");

                    b.HasIndex("IdPermissao");

                    b.ToTable("PapeisPermissoes");
                });

            modelBuilder.Entity("SistemaAdministracao.Models.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("IdSistema")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SistemaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SistemaId");

                    b.ToTable("Permissoes");
                });

            modelBuilder.Entity("SistemaAdministracao.Models.Sistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sistemas");
                });

            modelBuilder.Entity("SistemaAdministracao.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaAdministracao.Models.UsuarioPapel", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdPapel")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuario", "IdPapel");

                    b.HasIndex("IdPapel");

                    b.ToTable("UsuariosPapeis");
                });

            modelBuilder.Entity("SistemaAdministracao.Models.Papel", b =>
                {
                    b.HasOne("SistemaAdministracao.Models.Sistema", "Sistema")
                        .WithMany("Papeis")
                        .HasForeignKey("IdSistema")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SistemaAdministracao.Models.PapelPermissao", b =>
                {
                    b.HasOne("SistemaAdministracao.Models.Papel", "Papel")
                        .WithMany("PapeisPermissoes")
                        .HasForeignKey("IdPapel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAdministracao.Models.Permissao", "Permissao")
                        .WithMany("PapeisPermissoes")
                        .HasForeignKey("IdPermissao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Papel");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("SistemaAdministracao.Models.Permissao", b =>
                {
                    b.HasOne("SistemaAdministracao.Models.Sistema", "Sistema")
                        .WithMany("Permissoes")
                        .HasForeignKey("SistemaId");

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SistemaAdministracao.Models.UsuarioPapel", b =>
                {
                    b.HasOne("SistemaAdministracao.Models.Papel", "Papel")
                        .WithMany("UsuariosPapeis")
                        .HasForeignKey("IdPapel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAdministracao.Models.Usuario", "Usuario")
                        .WithMany("UsuariosPapeis")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Papel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaAdministracao.Models.Papel", b =>
                {
                    b.Navigation("PapeisPermissoes");

                    b.Navigation("UsuariosPapeis");
                });

            modelBuilder.Entity("SistemaAdministracao.Models.Permissao", b =>
                {
                    b.Navigation("PapeisPermissoes");
                });

            modelBuilder.Entity("SistemaAdministracao.Models.Sistema", b =>
                {
                    b.Navigation("Papeis");

                    b.Navigation("Permissoes");
                });

            modelBuilder.Entity("SistemaAdministracao.Models.Usuario", b =>
                {
                    b.Navigation("UsuariosPapeis");
                });
#pragma warning restore 612, 618
        }
    }
}
